name: nightly-features
description: Test enabled Rust nightly features against an allowlist

branding:
  icon: zap
  color: gray-dark

inputs:
  allowed_features:
    description: >
      Allowed Rust nightly features. Provide a comma-separated list.

      For example: asm, naked_functions, raw_ref_macros, ptr_offset_from
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
        python3 -m pip install --upgrade pip -qqq
        python3 -m pip install toml -qqq
      shell: bash
    - run: $GITHUB_ACTION_PATH/allowed-nightly-features "${{ inputs.allowed_features }}"
      shell: bash
